version: '3.8'

services:
  swarm-homepage:
    # To build locally instead of using pre-built image, uncomment the next line:
    # build: .
    image: ghcr.io/remotephone/swarm-homepage:latest
    container_name: swarm-homepage
    ports:
      - "5000:5000"
    environment:
      # Traefik API URL (if using Traefik API for service discovery)
      - TRAEFIK_API_URL=http://traefik:8080/api
      # Docker socket path
      - DOCKER_SOCKET=unix://var/run/docker.sock
      # Refresh interval in seconds
      - REFRESH_INTERVAL=60
      - PORT=5000
    volumes:
      # Mount Docker socket for service discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.localhost`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=5000"
      # Homepage labels (for self-discovery)
      - "homepage.name=Swarm Homepage"
      - "homepage.description=Docker Swarm Services Dashboard"
      - "homepage.category=Infrastructure"
    restart: unless-stopped

networks:
  traefik:
    external: true
